module.exports =
  method : 'GET'
  path   : '/api/v1/genres'

  config:
    description: "Returns a list of genres"
    plugins: "hapi-swagger": responseMessages: [
      { code: 500, message: 'Internal Server Error'}
    ]
    tags   : [ "api", "v1" ]

  handler: ( request, reply )->

    reply [
      "Ambient"
      "Ambient House"
      "Ambient Techno"
      "Dark Ambient"
      "Drone Music"
      "Psybient"
      "Space Music"
      "Italo House"
      "Breakbeat"
      "Baltimore Club"
      "Big Beat"
      "Broken Beat"
      "Breaks"
      "Nu Skool Breaks"
      "Progressive Breaks"
      "Trap"
      "Disco"
      "Cosmic Disco"
      "Blues"
      "Pop"
      "Country"
      "Folk"
      "Eurobeat"
      "Eurodance"
      "Euro Disco"
      "Soul"
      "R&B"
      "Hi-NRG"
      "Latin"
      "Italo Dance"
      "Nu-Disco"
      "Indie Dance"
      "Spacesynth"
      "Downtempo"
      "Acid"
      "Balearic Beat"
      "Chill Out"
      "Ethinc Electonica"
      "Glitch"
      "Illbient"
      "Techno"
      "New Age Music"
      "Nu Jazz"
      "Trip Hop"
      "Electonic Music"
      "Analogue & Digital"
      "Berlin School"
      "Electroacoustic"
      "Electro"
      "Electro-hop"
      "Electro Backbeat"
      "Freestyle Music"
      "Elctronica"
      "Electropop"
      "Folktronica"
      "Glitch"
      "IDM"
      "Nu Jazz"
      "Trip Hop"
      "Garage"
      "2-Step"
      "4x4"
      "Bassline"
      "Breakstep"
      "Dubstep"
      "Funk"
      "Grime"
      "Speed Garage"
      "Hardcore"
      "Hard Dance"
      "Bouncy Tempo"
      "Breakbeat Hardcore"
      "Breakcore"
      "Darkcore"
      "Doomcore"
      "Freeform"
      "Gabber"
      "Happy Hardcore"
      "Hardstyle"
      "Jumpstyle"
      "Makina"
      "Noisecore"
      "Speedcore"
      "Terrorcore"
      "UK Hardcore"
      "Hip Hop"
      "House"
      "Acid"
      "Rock"
      "Bubblegum Dance"
      "Chicago House"
      "Dark House"
      "Deep House"
      "Disco House"
      "Electro House"
      "Fidget House"
      "French House"
      "Freestyle House"
      "(US)Garage"
      "Ghetto"
      "Grind"
      "Hi-NRG"
      "Jazz"
      "(UK)Hard House"
      "Hip House"
      "Italo House"
      "Jackin House"
      "Kwaito"
      "Latin House"
      "Merenhouse"
      "Minimal House/Microhouse"
      "Progressive House"
      "Scouse House"
      "Electronica"
      "Skacid"
      "Tribal House"
      "Tech House"
      "Industrial"
      "Aggrotech"
      "Ambient Industrial"
      "Cybergrind"
      "Dark Ambient"
      "Dark Electro"
      "Death Industrial"
      "Electronic Body Music"
      "Electro-Industrial"
      "Futurepop"
      "DnB"
      "Metal"
      "Industrial Techno"
      "Japanoise"
      "Martial Industrial"
      "Neofolk"
      "Noise"
      "Power Noise"
      "Jungle/Drum & Bass"
      "Clownstep"
      "Darkstep"
      "Drumfunk"
      "Hardstep"
      "Intelligent DnB"
      "Jump-Up"
      "Liquid Funk"
      "Neurofunk"
      "Raggacore"
      "Sambass"
      "Techstep"
      "Trancestep"
      "Punk"
      "Alternative Dance"
      "Ambient Rock"
      "Cyber Metal"
      "Dance-Punk"
      "Dark Wave"
      "Digital Hardcore"
      "Electroclash"
      "Electro Rock"
      "Electropunk"
      "Ethereal Wave"
      "Industrial Rock"
      "Industrial Metal"
      "New Rave"
      "New Wave"
      "Progressive Rock"
      "Synthpop"
      "Synthpunk"
      "Detroit"
      "Dub"
      "Free Tekno"
      "Ghettotech"
      "Jtek/J-Tec"
      "Minimal"
      "New Beat"
      "Nortec"
      "Schranz"
      "Wonky Techno"
      "Trance"
      "Acid"
      "Ambient Trance"
      "Classic"
      "Vinyl"
      "Traktor"
      "Ableton"
      "Dream Trance"
      "Euro-Trance"
      "Hard Trance"
      "Hardstyle"
      "Nu-NRG"
      "Progressive Trance"
      "Tech Trance"
      "Uplifting Trance"
      "Vocal Trance"
      "Hard Trance"
      "Psy-Trance"
      "Dark Psy"
      "Full On"
      "Nitzhonot"
      "Psyprog"
      "Psybient"
      "Psybreaks"
      "South African Psytrance"
      "Suomisaundi"
      "Nu Rave"
      "Hardcore Breaks"
      "Rave Breaks"
      "Jungle Techno"
      "Chiptune"
      "8-Bit"
      "Bitpop"
      "Demoscene Music"
      "Nintendocore"
      "Picopop"
      "Game Boy Music"
      "Gamewave"
      "Oldschool Jungle"
      "Ragga-Jungle"
      "Intelligent Jungle"
      "Darkside Jungle"
    ]